config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' }

  resources :users, only: [:index, :show, :destroy, :edit, :update] do
    member do
      patch :ban
      patch :resend_confirmation_instructions
      patch :resend_invitation
    end
  end

  root 'static_pages#landing_page'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/roleable.rb
module Roleable
  extend ActiveSupport::Concern
  included do
    # List user roles
    ROLES = [:admin, :teacher, :student]

    # json column to store roles
    store_accessor :roles, *ROLES

    # Cast roles to/from booleans
    ROLES.each do |role|
      scope role, -> { where("roles @> ?", {role => true}.to_json) }
      define_method(:"#{role}=") { |value| super ActiveRecord::Type::Boolean.new.cast(value) }
      define_method(:"#{role}?") { send(role) }
    end

    def active_roles # Where value true
      ROLES.select { |role| send(:"#{role}?") }.compact
    end

    # role validation
    validate :must_have_a_role, on: :update
    validate :must_have_an_admin

    private

    def must_have_an_admin
      if (
        persisted? &&
        (User.where.not(id: id).pluck(:roles).count { |h| h['admin'] == true } < 1) &&
        roles_changed? &&
        admin == false
      )
        errors.add(:base, 'There should be at least one admin')
      end
    end

    def must_have_a_role
      if roles.values.none?
        errors.add(:base, 'A user must have at least one role')
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable, :lockable

  include Roleable

  after_create do
    # assign default role
    self.update(student: true)
  end

  def to_s
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    user_path(resource)
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private

  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource) # In case you want to sign in the user
    root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing_page
  end

  def privacy_policy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin, only: [
    :edit,
    :update,
    :ban,
    :destroy,
    :resend_confirmation_instructions
  ]
  before_action :require_admin_or_inviter, only: [:resend_invitation]

  def index
    @users = User.all.order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def resend_confirmation_instructions
    @user = User.find(params[:id])
    if !@user.confirmed? && !@user.created_by_invite?
      @user.resend_confirmation_instructions
      redirect_to @user, notice: 'Confirmation instructions were resent'
    else
      redirect_to @user, notice: 'User already confirmed'
    end
  end

  def resend_invitation
    @user = User.find(params[:id])
    if @user.created_by_invite? && !@user.invitation_accepted? && !@user.confirmed?
      @user.invite!
      redirect_to @user, notice: 'Invitation was resent'
    else
      redirect_to @user, notice: 'User already confirmed'
    end
  end

  def ban
    @user = User.find(params[:id])
    redirect_to @user, notice: 'You can not ban yourself' if @user == current_user
    if @user.access_locked?
      @user.unlock_access!
    else
      @user.lock_access!
    end
    redirect_to @user, notice: "User access locked: #{@user.access_locked?}"
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: 'User was successfully destroyed'
  end

  private

  def user_params
    params.require(:user).permit(*User::ROLES)
  end

  def require_admin
    unless current_user.admin?
      redirect_to root_path, alert: 'You are not authorized to perform this action'
    end
  end

  def require_admin_or_inviter
    @user = User.find(params[:id])
    unless current_user.admin? || @user.invited_by == current_user
      redirect_to root_path, alert: 'You are not authorized to perform this action'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def ban_status(user)
    user.access_locked? ? 'Unban' : 'Ban'
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <i class="fas fa-flag"></i>
      Brand
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%= link_to root_path, class: "nav-link #{'active fw-bold' if current_page?(root_path)}" do %>
          <div class="fa fa-home"></div>
          Home
        <% end %>
        <%= link_to users_path, class: "nav-link #{'active fw-bold' if current_page?(users_path)}" do %>
          <div class="fa fa-users"></div>
          Users
        <% end %>
        <%= link_to new_user_invitation_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_invitation_path)}" do %>
          <div class="fa fa-plus"></div>
          <div class="fa fa-user"></div>
          Invite User
        <% end %>
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <div class="fa fa-user"></div>
              <b><%= current_user.email %></b>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to user_path(current_user), class: "dropdown-item #{'active fw-bold' if current_page?(user_path(current_user))}" do %>
                <div class="fa fa-user"></div>
                My profile
              <% end %>
              <%= link_to edit_user_registration_path, class: "dropdown-item #{'active fw-bold' if current_page?(edit_user_registration_path)}" do %>
                <div class="fa fa-cog"></div>
                <b>Account settings</b>
              <% end %>
              <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                <div class="fa fa-sign-out-alt"></div>
                <b>Sign out</b>
              <% end %>
            </ul>
          </li>
        <% else %>
          <%= link_to "Log in", new_user_session_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_session_path)}" %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_registration_path)}" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
    <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>');
    <% end %>
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Devise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/messages" %>
    <div class="container">
      <br />
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/landing_page.html.erb
<div class="container">
  <h1>Hello World</h1>
  <%= link_to "Privacy Policy", privacy_policy_path %>
</div>

app/views/static_pages/privacy_policy.html.erb
<h1>StaticPages#privacy_policy</h1>
<p>Find me in app/views/static_pages/privacy_policy.html.erb</p>
<%= link_to "Landing Page", root_path %>

app/views/users/_user.html.erb
<b>Id: </b>
<%= link_to user.id, user_path(user) %>
<br />

<b>Email: </b>
<%= user.email %>
<br />

<b>Confirmation: </b>
<%= user.confirmed? %>
<br />

<b>Sign in count: </b>
<%= user.sign_in_count %>
<br />

<b>Current sign in at: </b>
<%= user.current_sign_in_at %>
<br />

<b>Last sign in at: </b>
<%= user.last_sign_in_at %>
<br />

<b>Current sign in ip: </b>
<%= user.current_sign_in_ip %>
<br />

<b>Last sign in ip: </b>
<%= user.last_sign_in_ip %>
<br />

<b>Locked at: </b>
<%= user.locked_at %>
<br />

<b>Roles: </b>
<%= user.active_roles.join(", ") %>
<br>

<% if user.created_by_invite? %>
  <b>Invited by: </b>
  <%= user.invited_by %>
  <br>

  <b>Invitation accepted?: </b>
  <%= user.invitation_accepted? %>
  <br>

  <% if current_user.admin? || user.invited_by == current_user %>
    <% if user.created_by_invite? && !user.invitation_accepted? && !user.confirmed? %>
      <%= link_to "Resend invitation", resend_invitation_user_path(user), method: :patch %>
    <% end %>
  <% end %>
<% end %>

<% if current_user.admin? %>
  <%= link_to "Edit roles", edit_user_path(user) %>
  <% if !user.confirmed? && !user.created_by_invite? %>
    <%= link_to "Resend confirmation instructions", resend_confirmation_instructions_user_path(user), method: :patch %>
  <% end %>
  <%= link_to ban_status(user), ban_user_path(user), method: :patch %>
  <%= link_to "Delete", user, method: :delete, data: {confirm: "Are you sure"} %>
<% end %>

app/views/users/edit.html.erb
<h2>
  Editing roles for <%= @user %> 
</h2> 

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% User::ROLES.each do |role| %>
    <label>
      <%= f.check_box role %>
      <%= role.to_s.humanize %>
    </label>
    <br>
  <% end %>

  <%= f.button :submit %>
<% end %>

<%= link_to "Cancel", user_path(@user) %>

app/views/users/index.html.erb
All users
(<%= @users.size %>)
<% @users.each do |user| %>
  <hr />
  <%= render "users/user", user: user %>
<% end %>

app/views/users/show.html.erb
<%= render "users/user", user: @user %>
<br />
<%= link_to "All Users", users_path %>